language: python
dist: trusty
sudo: false
cache: pip
python:
    - 2.7
    - 3.5
    - pypy-5.3.1
install:
    - pip install -U 'setuptools>=18.5' 'pip>=6.0'
    # Need to install performance, performance/tests/test_compare.py imports it
    - pip install -e .
script:
    - python runtests.py
notifications:
  email:
    - victor.stinner@gmail.com
