[project]
name = "pyperformance_bm_fastapi"
requires-python = ">=3.10"
dependencies = [
    "pyperf",
    "fastapi",
    "uvicorn",
    "httpx",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "fastapi"
tags = "apps"
