[project]
name = "pyperformance_bm_regex_compile"
requires-python = ">=3.8"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "regex_compile"
tags = "regex"
