[project]
name = "pyperformance_bm_sqlalchemy_imperative"
requires-python = ">=3.8"
dependencies = [
    "pyperf",
    "SQLAlchemy",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "sqlalchemy_imperative"
