[project]
name = "pyperformance_bm_random"
requires-python = ">=3.12"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "random"
tags = "math"
