[project]
name = "pyperformance_bm_asyncio_tcp"
requires-python = ">=3.8"
dependencies = ["pyperf"]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "asyncio_tcp"
tags = "asyncio"
