name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Midnight UTC:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        # Test all supported versions on Ubuntu:
        os: [ubuntu-latest]
        python: ["3.7", "3.8", "3.9", "3.10", 3.11-dev]
        include:
          # Also test PyPy, macOS, and Windows:
          - os: ubuntu-latest
            python: pypy3
          - os: macos-latest
            python: "3.10"
          # XXX: We should be testing 3.10, but for some reason setuptools can't
          # seem to find the runner's C compiler for new wheel builds... 
          - os: windows-latest
            python: "3.9"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install
      # pyperformance must be installed:
      # pyperformance/tests/test_compare.py imports it
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -e .
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Run Tests
      run: python -u -m pyperformance.tests
