name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Midnight UTC:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        # Test all supported versions on Ubuntu:
        os: [ubuntu-latest]
        python: ["3.7", "3.8", "3.9", "3.10", 3.11-dev, 3.12-dev]
        include:
          # Also test PyPy, macOS, and Windows:
          - os: ubuntu-latest
            python: pypy-3.9
          - os: ubuntu-latest
            python: pypy-3.8
          - os: ubuntu-latest
            python: pypy-3.7
          - os: macos-latest
            python: "3.10"
          - os: windows-latest
            python: "3.10"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      if: "!endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python ${{ matrix.python }} using deadsnakes
      uses: deadsnakes/action@v2.1.1
      if: "endsWith(matrix.python, '-dev')"
      with:
        python-version: ${{ matrix.python }}
    - name: Install
      # pyperformance must be installed:
      # pyperformance/tests/test_compare.py imports it
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -e .
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Run Tests
      run: python -u -m pyperformance.tests
